// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHw-pqU1_CxKpvGUAVSoVBcK2BXKiZrK8',
    appId: '1:372329092725:web:82bde15448bef71f810a3c',
    messagingSenderId: '372329092725',
    projectId: 'artesanias-andinas',
    authDomain: 'artesanias-andinas.firebaseapp.com',
    storageBucket: 'artesanias-andinas.firebasestorage.app',
    measurementId: 'G-5JHN3WWLYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ca3dDn6Kf9Jo_jVlid0k-1gaA0WQxeM',
    appId: '1:372329092725:android:0a81058d93f6b858810a3c',
    messagingSenderId: '372329092725',
    projectId: 'artesanias-andinas',
    storageBucket: 'artesanias-andinas.firebasestorage.app',
  );
}
