// Mocks generated by Mockito 5.4.6 from annotations
// in artesanias_andinas/test/features/location/location_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:artesanias_andinas/core/errors/failures.dart' as _i5;
import 'package:artesanias_andinas/features/location/domain/entities/location_entity.dart'
    as _i6;
import 'package:artesanias_andinas/features/location/domain/repositories/location_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LocationEntity>>
      getCurrentLocation() => (super.noSuchMethod(
            Invocation.method(
              #getCurrentLocation,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.LocationEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i6.LocationEntity>(
              this,
              Invocation.method(
                #getCurrentLocation,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.LocationEntity>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i6.LocationEntity>> watchLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchLocation,
          [],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.Failure, _i6.LocationEntity>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, _i6.LocationEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkLocationPermission,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #checkLocationPermission,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> requestLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #requestLocationPermission,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
